### ISSUE TITLE
doc: add section imagick or gd library php.ini

### ISSUE THREAD

**Issue by Grezor** [quentinsvn/barcodefinder#1]
Hello @quentinsvn, 
It asks for the extension imagick or gd library php. It should be informed in the readme. If it is an extension to be activated in the php.ini

https://ourcodeworld.com/articles/read/349/how-to-install-and-enable-the-imagick-extension-in-xampp-for-windows

**Comment by quentinsvn** [comment]
Hello @Grezor ,

This is certainly due to the fact that the dependency allowing to generate the barcodes of the products needs additional PHP modules (in particular at the level of the treatment of the images). 

It is therefore necessary to install and/or activate the "[Imagick](https://www.php.net/manual/fr/class.imagick)" and "[gd-lib](https://www.php.net/manual/fr/book.image.php)" modules from the php.ini file of your web server. 

This information will be added soon in the "Necessary tools" section of the project README.

Thank you for your feedback !
